service: aws-node-typescript-apollo-lambda

plugins:
  # - serverless-dotenv-plugin
  - serverless-offline
  # - serverless-plugin-typescript
  # - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 15
  stage: dev

# custom:
#   includeDependencies:
#     always:
#       - 'dist/__generated__/**' # (optional) always include these globs and their dependencies

package:
  individually: true

functions:
  graphql:
    handler: dist/serverless/handler.handler
    events:
      - http:
          private: false
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          private: false
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
