service: aws-node-typescript-apollo-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 15

functions:
  graphql:
    handler: src/serverless/handler.graphqlHandler
    events:
      - http:
          private: false
          path: graphql
          method: post
          cors: true
      - http:
          private: false
          path: graphql
          method: get
          cors: true
